export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT"
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT"
export const UPDATE_USER_INFO = "UPDATE_USER_INFO"
export const SAVE_INFO = "SAVE_INFO"
export const API_KEY = "AIzaSyCVKdcggTKteAiAm2KT6Bms9Qb9yxBL2jI"